import Foundation

extension DefaultWorkoutsCrossfit {

    static func openWodsDefaults() -> [DefaultWorkoutSeed] {
        return [
            DefaultWorkoutSeed(name: "OPEN 11.1", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 11.2", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 11.3", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 11.4", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 11.5", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 12.1", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 12.2", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 12.3", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 12.4", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 12.5", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 13.1", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 13.2", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 13.3", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 13.4", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 13.5", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 14.1", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 14.2", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 14.3", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 14.4", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 14.5", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 15.1", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 15.1A", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 15.2", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 15.3", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 15.4", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 15.5", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 16.1", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 16.2", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 16.3", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 16.4", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 16.5", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 17.1", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 17.2", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 17.3", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 17.4", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 17.5", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 18.1", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 18.2", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 18.2A", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 18.3", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 18.4", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 18.5", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 19.1", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 19.2", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 19.3", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 19.4", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 19.5", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 20.1", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 20.2", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 20.3", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 20.4", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 20.5", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 21.1", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 21.2", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 21.3", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 21.3A", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 21.4", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 21.5", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 22.1", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 22.2", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 22.3", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 22.4", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 22.5", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 23.1", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 23.2", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 23.3", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 23.4", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 23.5", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 24.1", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 24.2", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OPEN 24.3", category: .crossfit, sectionKey: "openWods", blockOrders: [1, 2, 3, 4, 5])
        ]
    }
}
