import Foundation

extension DefaultWorkoutsCrossfit {

    static func heroTributeWorkoutsDefaults() -> [DefaultWorkoutSeed] {
        return [
            DefaultWorkoutSeed(name: "JT (2005)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "MICHAEL (2005)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "MURPH (2005)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "DANIEL (2005)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "JOSH (2006)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "RANDY (2008)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "JASON (2008)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "BADGER (2008)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "DT (2009)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "NATE (2009)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "RYAN (2009)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "HANSEN (2009)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "JERRY (2009)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "HOLBROOK (2010)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "WHITTEN (2010)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "LUMBERJACK 20 (2010)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "GARRETT (2010)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "BLANCHARD (2010)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "BULL (2010)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "MOORE (2010)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "GLEN (2010)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "COLLIN (2010)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "ADAM BROWN (2010)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "ANDY (2010)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "ALEXANDER (2010)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "CAMERON (2010)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "ERIN (2010)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "HAMILTON (2013)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "HELTON (2010)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "HORTON (2015)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "JACK (2010)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "JAKE (2011)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "KALSU (2011)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "LEE (2012)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "LOREDO (2012)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "LUCAS (2012)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "LUCE (2012)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "MARCO (2011)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "MARSTON (2011)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "MATHEW (2011)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "MAUPIN (2011)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "MCCLUSKEY (2012)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "MCGHEE (2012)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "NELSON (2012)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "OMAR (2013)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "PAT (2013)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "RANKEL (2013)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "RAUF (2013)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "RILEY (2013)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "ROY (2013)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "SAMAN (2013)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "SCHMIDT (2014)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "SEÁN (2014)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "SHIP (2014)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "SMALL (2014)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "STEPHEN (2015)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "STRANG (2015)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "SUAREZ (2015)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "TAYLOR (2015)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "THE SEVEN (2015)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "THOMPSON (2015)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "TOMMY V (2016)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "TRAVIS MANION (2016)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "TULLY (2016)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "WALSH (2016)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "WHITE (2016)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "WOOD (2017)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "WRIGHT (2017)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "ZEMBIEC (2017)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "BURIAK (2020)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "GOOSE (2021)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "GALE FORCE (2022)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "ODA 7313 (2023)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5]),
            DefaultWorkoutSeed(name: "NORTHRUP (2024)", category: .crossfit, sectionKey: "heroTributeWorkouts", blockOrders: [1, 2, 3, 4, 5])
        ]
    }
}
